[package]
name = "app_example"
version = "0.1.0"
edition = "2021"

[lib]
name = "app_example"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
env_logger = "0.10"
faisca = { path = "../faisca-rs" }
log = "0.4"